query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    title
    author {
      ... on Author {
        name
        bio
        hobbies
        image
      }
      ... on Document {
        id
      }
      ... on Document {
        _internalSys: _sys {
          path
        }
      }
    }
    categories
    body
    image
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ... on Document {
      _internalSys: _sys {
        path
      }
    }
  }
}
