/* eslint-disable */

export const AllTypesProps: Record<string, any> = {
  Reference: 'String',
  JSON: 'String',
  SystemInfo: {
    breadcrumbs: {
      excludeExtension: {
        type: 'Boolean',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
  },
  Query: {
    getOptimizedQuery: {
      queryString: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    collection: {
      collection: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    node: {
      id: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    document: {
      collection: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    documentConnection: {
      before: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      after: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      first: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      last: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      sort: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      filter: {
        type: 'DocumentFilter',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    localeInfo: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    localeInfoConnection: {
      before: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      after: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      first: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      last: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      sort: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      filter: {
        type: 'LocaleInfoFilter',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    news: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    newsConnection: {
      before: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      after: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      first: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      last: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      sort: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      filter: {
        type: 'NewsFilter',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    footer: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    footerConnection: {
      before: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      after: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      first: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      last: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      sort: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      filter: {
        type: 'FooterFilter',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    theme: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    themeConnection: {
      before: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      after: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      first: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      last: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      sort: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      filter: {
        type: 'ThemeFilter',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    navigation: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    navigationConnection: {
      before: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      after: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      first: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      last: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      sort: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      filter: {
        type: 'NavigationFilter',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    page: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    pageConnection: {
      before: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      after: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      first: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      last: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      sort: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      filter: {
        type: 'PageFilter',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
  },
  StringFilter: {
    startsWith: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    eq: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    exists: {
      type: 'Boolean',
      array: false,
      arrayRequired: false,
      required: false,
    },
    in: {
      type: 'String',
      array: true,
      arrayRequired: false,
      required: false,
    },
  },
  LocaleInfoAuFilter: {
    tel: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLink: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLinkPersonal: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signInLink: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  LocaleInfoUsFilter: {
    tel: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLink: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLinkPersonal: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signInLink: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  LocaleInfoGbFilter: {
    tel: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLink: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLinkPersonal: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signInLink: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  LocaleInfoFilter: {
    au: {
      type: 'LocaleInfoAuFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    us: {
      type: 'LocaleInfoUsFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    gb: {
      type: 'LocaleInfoGbFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  DatetimeFilter: {
    after: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    before: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    eq: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    exists: {
      type: 'Boolean',
      array: false,
      arrayRequired: false,
      required: false,
    },
    in: {
      type: 'String',
      array: true,
      arrayRequired: false,
      required: false,
    },
  },
  RichTextFilter: {
    startsWith: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    eq: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    exists: {
      type: 'Boolean',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  NewsFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    image: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    publishDate: {
      type: 'DatetimeFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    category: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    body: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  FooterOfficesFilter: {
    location: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    address: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    phone: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  FooterDisclaimersFilter: {
    body: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  FooterFilter: {
    offices: {
      type: 'FooterOfficesFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    disclaimers: {
      type: 'FooterDisclaimersFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  ThemeFilter: {
    displayFont: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    colorMode: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageSeoFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    image: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksNewsNewsItemsArticleFilter: {
    news: {
      type: 'NewsFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksNewsNewsItemsFilter: {
    article: {
      type: 'PageBlocksNewsNewsItemsArticleFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksNewsFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    newsItems: {
      type: 'PageBlocksNewsNewsItemsFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksStatsWithImageStatsFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksStatsWithImageFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    image: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    stats: {
      type: 'PageBlocksStatsWithImageStatsFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  ImageFilter: {
    startsWith: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    eq: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    exists: {
      type: 'Boolean',
      array: false,
      arrayRequired: false,
      required: false,
    },
    in: {
      type: 'String',
      array: true,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksHeroActionFilter: {
    callToAction: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkText: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkOverride: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryText: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLink: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLinkOverride: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksHeroFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    image: {
      type: 'ImageFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    action: {
      type: 'PageBlocksHeroActionFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksSlideshowItemsActionFilter: {
    callToAction: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkText: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkOverride: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryText: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLink: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLinkOverride: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksSlideshowItemsOverlayFilter: {
    image: {
      type: 'ImageFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayColor: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayOpacity: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksSlideshowItemsFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    action: {
      type: 'PageBlocksSlideshowItemsActionFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlay: {
      type: 'PageBlocksSlideshowItemsOverlayFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksSlideshowFilter: {
    items: {
      type: 'PageBlocksSlideshowItemsFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableItemsMetaAFilter: {
    aOne: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableItemsMetaBFilter: {
    bOne: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableItemsMetaFilter: {
    a: {
      type: 'PageBlocksComparisonTableItemsMetaAFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    b: {
      type: 'PageBlocksComparisonTableItemsMetaBFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableItemsFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    bulletPoints: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    meta: {
      type: 'PageBlocksComparisonTableItemsMetaFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableActionFilter: {
    callToAction: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkText: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkOverride: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryText: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLink: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLinkOverride: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    items: {
      type: 'PageBlocksComparisonTableItemsFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    action: {
      type: 'PageBlocksComparisonTableActionFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFeatureFeaturesFilter: {
    icon: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    name: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFeatureOverlayFilter: {
    image: {
      type: 'ImageFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayColor: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayOpacity: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFeatureFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    featureStyle: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    features: {
      type: 'PageBlocksFeatureFeaturesFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlay: {
      type: 'PageBlocksFeatureOverlayFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFullScreenLogoOverlayFilter: {
    image: {
      type: 'ImageFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayColor: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayOpacity: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFullScreenLogoFilter: {
    slogan: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlay: {
      type: 'PageBlocksFullScreenLogoOverlayFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFullScreenHeaderActionFilter: {
    callToAction: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkText: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkOverride: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryText: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLink: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLinkOverride: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFullScreenHeaderOverlayFilter: {
    image: {
      type: 'ImageFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayColor: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayOpacity: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFullScreenHeaderFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'RichTextFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    action: {
      type: 'PageBlocksFullScreenHeaderActionFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlay: {
      type: 'PageBlocksFullScreenHeaderOverlayFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFilter: {
    news: {
      type: 'PageBlocksNewsFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    statsWithImage: {
      type: 'PageBlocksStatsWithImageFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    hero: {
      type: 'PageBlocksHeroFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    slideshow: {
      type: 'PageBlocksSlideshowFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    comparisonTable: {
      type: 'PageBlocksComparisonTableFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    feature: {
      type: 'PageBlocksFeatureFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    fullScreenLogo: {
      type: 'PageBlocksFullScreenLogoFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    fullScreenHeader: {
      type: 'PageBlocksFullScreenHeaderFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageFilter: {
    title: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'StringFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    seo: {
      type: 'PageSeoFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    blocks: {
      type: 'PageBlocksFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  NavigationItemsPageFilter: {
    page: {
      type: 'PageFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  NavigationItemsFilter: {
    page: {
      type: 'NavigationItemsPageFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  NavigationFilter: {
    items: {
      type: 'NavigationItemsFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  DocumentFilter: {
    localeInfo: {
      type: 'LocaleInfoFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    news: {
      type: 'NewsFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    footer: {
      type: 'FooterFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    theme: {
      type: 'ThemeFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    navigation: {
      type: 'NavigationFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
    page: {
      type: 'PageFilter',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  Collection: {
    documents: {
      before: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      after: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      first: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      last: {
        type: 'Float',
        array: false,
        arrayRequired: false,
        required: false,
      },
      sort: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      filter: {
        type: 'DocumentFilter',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
  },
  Mutation: {
    addPendingDocument: {
      collection: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      template: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
    },
    updateDocument: {
      collection: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'DocumentMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    createDocument: {
      collection: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: false,
      },
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'DocumentMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    updateLocaleInfo: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'LocaleInfoMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    createLocaleInfo: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'LocaleInfoMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    updateNews: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'NewsMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    createNews: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'NewsMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    updateFooter: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'FooterMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    createFooter: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'FooterMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    updateTheme: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'ThemeMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    createTheme: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'ThemeMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    updateNavigation: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'NavigationMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    createNavigation: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'NavigationMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    updatePage: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'PageMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
    createPage: {
      relativePath: {
        type: 'String',
        array: false,
        arrayRequired: false,
        required: true,
      },
      params: {
        type: 'PageMutation',
        array: false,
        arrayRequired: false,
        required: true,
      },
    },
  },
  DocumentMutation: {
    localeInfo: {
      type: 'LocaleInfoMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    news: {
      type: 'NewsMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    footer: {
      type: 'FooterMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    theme: {
      type: 'ThemeMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    navigation: {
      type: 'NavigationMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    page: {
      type: 'PageMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  LocaleInfoAuMutation: {
    tel: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLink: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLinkPersonal: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signInLink: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  LocaleInfoUsMutation: {
    tel: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLink: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLinkPersonal: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signInLink: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  LocaleInfoGbMutation: {
    tel: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLink: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signUpLinkPersonal: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    signInLink: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  LocaleInfoMutation: {
    au: {
      type: 'LocaleInfoAuMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    us: {
      type: 'LocaleInfoUsMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    gb: {
      type: 'LocaleInfoGbMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  NewsMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    image: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    publishDate: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    category: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    body: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  FooterOfficesMutation: {
    location: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    address: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    phone: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  FooterDisclaimersMutation: {
    body: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  FooterMutation: {
    offices: {
      type: 'FooterOfficesMutation',
      array: true,
      arrayRequired: false,
      required: false,
    },
    disclaimers: {
      type: 'FooterDisclaimersMutation',
      array: true,
      arrayRequired: false,
      required: false,
    },
  },
  ThemeMutation: {
    displayFont: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    colorMode: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  NavigationItemsMutation: {
    page: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  NavigationMutation: {
    items: {
      type: 'NavigationItemsMutation',
      array: true,
      arrayRequired: false,
      required: false,
    },
  },
  PageSeoMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    image: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksNewsNewsItemsMutation: {
    article: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksNewsMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
    newsItems: {
      type: 'PageBlocksNewsNewsItemsMutation',
      array: true,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksStatsWithImageStatsMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksStatsWithImageMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
    image: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    stats: {
      type: 'PageBlocksStatsWithImageStatsMutation',
      array: true,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksHeroActionMutation: {
    callToAction: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkText: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkOverride: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryText: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLink: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLinkOverride: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksHeroMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
    image: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    action: {
      type: 'PageBlocksHeroActionMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksSlideshowItemsActionMutation: {
    callToAction: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkText: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkOverride: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryText: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLink: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLinkOverride: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksSlideshowItemsOverlayMutation: {
    image: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayColor: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayOpacity: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksSlideshowItemsMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
    action: {
      type: 'PageBlocksSlideshowItemsActionMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlay: {
      type: 'PageBlocksSlideshowItemsOverlayMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksSlideshowMutation: {
    items: {
      type: 'PageBlocksSlideshowItemsMutation',
      array: true,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableItemsMetaAMutation: {
    aOne: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableItemsMetaBMutation: {
    bOne: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableItemsMetaMutation: {
    a: {
      type: 'PageBlocksComparisonTableItemsMetaAMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    b: {
      type: 'PageBlocksComparisonTableItemsMetaBMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableItemsMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
    bulletPoints: {
      type: 'String',
      array: true,
      arrayRequired: false,
      required: false,
    },
    meta: {
      type: 'PageBlocksComparisonTableItemsMetaMutation',
      array: true,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableActionMutation: {
    callToAction: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkText: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkOverride: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryText: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLink: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLinkOverride: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksComparisonTableMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
    items: {
      type: 'PageBlocksComparisonTableItemsMutation',
      array: true,
      arrayRequired: false,
      required: false,
    },
    action: {
      type: 'PageBlocksComparisonTableActionMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFeatureFeaturesMutation: {
    icon: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    name: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFeatureOverlayMutation: {
    image: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayColor: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayOpacity: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFeatureMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
    featureStyle: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    features: {
      type: 'PageBlocksFeatureFeaturesMutation',
      array: true,
      arrayRequired: false,
      required: false,
    },
    overlay: {
      type: 'PageBlocksFeatureOverlayMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFullScreenLogoOverlayMutation: {
    image: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayColor: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayOpacity: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFullScreenLogoMutation: {
    slogan: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlay: {
      type: 'PageBlocksFullScreenLogoOverlayMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFullScreenHeaderActionMutation: {
    callToAction: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkText: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    linkOverride: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryText: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLink: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    secondaryLinkOverride: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFullScreenHeaderOverlayMutation: {
    image: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayColor: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlayOpacity: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksFullScreenHeaderMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    subTitle: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    description: {
      type: 'JSON',
      array: false,
      arrayRequired: false,
      required: false,
    },
    action: {
      type: 'PageBlocksFullScreenHeaderActionMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    overlay: {
      type: 'PageBlocksFullScreenHeaderOverlayMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageBlocksMutation: {
    news: {
      type: 'PageBlocksNewsMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    statsWithImage: {
      type: 'PageBlocksStatsWithImageMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    hero: {
      type: 'PageBlocksHeroMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    slideshow: {
      type: 'PageBlocksSlideshowMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    comparisonTable: {
      type: 'PageBlocksComparisonTableMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    feature: {
      type: 'PageBlocksFeatureMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    fullScreenLogo: {
      type: 'PageBlocksFullScreenLogoMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    fullScreenHeader: {
      type: 'PageBlocksFullScreenHeaderMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
  },
  PageMutation: {
    title: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    link: {
      type: 'String',
      array: false,
      arrayRequired: false,
      required: false,
    },
    seo: {
      type: 'PageSeoMutation',
      array: false,
      arrayRequired: false,
      required: false,
    },
    blocks: {
      type: 'PageBlocksMutation',
      array: true,
      arrayRequired: false,
      required: false,
    },
  },
}

export const ReturnTypes: Record<string, any> = {
  SystemInfo: {
    filename: 'String',
    basename: 'String',
    breadcrumbs: 'String',
    path: 'String',
    relativePath: 'String',
    extension: 'String',
    template: 'String',
    collection: 'Collection',
  },
  PageInfo: {
    hasPreviousPage: 'Boolean',
    hasNextPage: 'Boolean',
    startCursor: 'String',
    endCursor: 'String',
  },
  Node: {
    '...on LocaleInfo': 'LocaleInfo',
    '...on News': 'News',
    '...on Footer': 'Footer',
    '...on Theme': 'Theme',
    '...on Navigation': 'Navigation',
    '...on Page': 'Page',
    id: 'ID',
  },
  Document: {
    '...on LocaleInfo': 'LocaleInfo',
    '...on News': 'News',
    '...on Footer': 'Footer',
    '...on Theme': 'Theme',
    '...on Navigation': 'Navigation',
    '...on Page': 'Page',
    id: 'ID',
    _sys: 'SystemInfo',
    _values: 'JSON',
  },
  Connection: {
    '...on DocumentConnection': 'DocumentConnection',
    '...on LocaleInfoConnection': 'LocaleInfoConnection',
    '...on NewsConnection': 'NewsConnection',
    '...on FooterConnection': 'FooterConnection',
    '...on ThemeConnection': 'ThemeConnection',
    '...on NavigationConnection': 'NavigationConnection',
    '...on PageConnection': 'PageConnection',
    totalCount: 'Float',
    pageInfo: 'PageInfo',
  },
  Query: {
    getOptimizedQuery: 'String',
    collection: 'Collection',
    collections: 'Collection',
    node: 'Node',
    document: 'DocumentNode',
    documentConnection: 'DocumentConnection',
    localeInfo: 'LocaleInfo',
    localeInfoConnection: 'LocaleInfoConnection',
    news: 'News',
    newsConnection: 'NewsConnection',
    footer: 'Footer',
    footerConnection: 'FooterConnection',
    theme: 'Theme',
    themeConnection: 'ThemeConnection',
    navigation: 'Navigation',
    navigationConnection: 'NavigationConnection',
    page: 'Page',
    pageConnection: 'PageConnection',
  },
  DocumentConnectionEdges: {
    cursor: 'String',
    node: 'DocumentNode',
  },
  DocumentConnection: {
    pageInfo: 'PageInfo',
    totalCount: 'Float',
    edges: 'DocumentConnectionEdges',
  },
  Collection: {
    name: 'String',
    slug: 'String',
    label: 'String',
    path: 'String',
    format: 'String',
    matches: 'String',
    templates: 'JSON',
    fields: 'JSON',
    documents: 'DocumentConnection',
  },
  DocumentNode: {
    '...on LocaleInfo': 'LocaleInfo',
    '...on News': 'News',
    '...on Footer': 'Footer',
    '...on Theme': 'Theme',
    '...on Navigation': 'Navigation',
    '...on Page': 'Page',
  },
  LocaleInfoAu: {
    tel: 'String',
    signUpLink: 'String',
    signUpLinkPersonal: 'String',
    signInLink: 'String',
  },
  LocaleInfoUs: {
    tel: 'String',
    signUpLink: 'String',
    signUpLinkPersonal: 'String',
    signInLink: 'String',
  },
  LocaleInfoGb: {
    tel: 'String',
    signUpLink: 'String',
    signUpLinkPersonal: 'String',
    signInLink: 'String',
  },
  LocaleInfo: {
    au: 'LocaleInfoAu',
    us: 'LocaleInfoUs',
    gb: 'LocaleInfoGb',
    id: 'ID',
    _sys: 'SystemInfo',
    _values: 'JSON',
  },
  LocaleInfoConnectionEdges: {
    cursor: 'String',
    node: 'LocaleInfo',
  },
  LocaleInfoConnection: {
    pageInfo: 'PageInfo',
    totalCount: 'Float',
    edges: 'LocaleInfoConnectionEdges',
  },
  News: {
    title: 'String',
    subTitle: 'String',
    image: 'String',
    publishDate: 'String',
    category: 'String',
    body: 'JSON',
    id: 'ID',
    _sys: 'SystemInfo',
    _values: 'JSON',
  },
  NewsConnectionEdges: {
    cursor: 'String',
    node: 'News',
  },
  NewsConnection: {
    pageInfo: 'PageInfo',
    totalCount: 'Float',
    edges: 'NewsConnectionEdges',
  },
  FooterOffices: {
    location: 'String',
    address: 'String',
    phone: 'String',
  },
  FooterDisclaimers: {
    body: 'JSON',
  },
  Footer: {
    offices: 'FooterOffices',
    disclaimers: 'FooterDisclaimers',
    id: 'ID',
    _sys: 'SystemInfo',
    _values: 'JSON',
  },
  FooterConnectionEdges: {
    cursor: 'String',
    node: 'Footer',
  },
  FooterConnection: {
    pageInfo: 'PageInfo',
    totalCount: 'Float',
    edges: 'FooterConnectionEdges',
  },
  Theme: {
    displayFont: 'String',
    colorMode: 'String',
    id: 'ID',
    _sys: 'SystemInfo',
    _values: 'JSON',
  },
  ThemeConnectionEdges: {
    cursor: 'String',
    node: 'Theme',
  },
  ThemeConnection: {
    pageInfo: 'PageInfo',
    totalCount: 'Float',
    edges: 'ThemeConnectionEdges',
  },
  NavigationItemsPage: {
    '...on Page': 'Page',
  },
  NavigationItems: {
    page: 'NavigationItemsPage',
  },
  Navigation: {
    items: 'NavigationItems',
    id: 'ID',
    _sys: 'SystemInfo',
    _values: 'JSON',
  },
  NavigationConnectionEdges: {
    cursor: 'String',
    node: 'Navigation',
  },
  NavigationConnection: {
    pageInfo: 'PageInfo',
    totalCount: 'Float',
    edges: 'NavigationConnectionEdges',
  },
  PageSeo: {
    title: 'String',
    image: 'String',
    description: 'String',
  },
  PageBlocksNewsNewsItemsArticle: {
    '...on News': 'News',
  },
  PageBlocksNewsNewsItems: {
    article: 'PageBlocksNewsNewsItemsArticle',
  },
  PageBlocksNews: {
    title: 'String',
    subTitle: 'String',
    description: 'JSON',
    newsItems: 'PageBlocksNewsNewsItems',
  },
  PageBlocksStatsWithImageStats: {
    title: 'String',
    subTitle: 'String',
    description: 'JSON',
  },
  PageBlocksStatsWithImage: {
    title: 'String',
    subTitle: 'String',
    description: 'JSON',
    image: 'String',
    stats: 'PageBlocksStatsWithImageStats',
  },
  PageBlocksHeroAction: {
    callToAction: 'String',
    linkText: 'String',
    link: 'String',
    linkOverride: 'String',
    secondaryText: 'String',
    secondaryLink: 'String',
    secondaryLinkOverride: 'String',
  },
  PageBlocksHero: {
    title: 'String',
    subTitle: 'String',
    description: 'JSON',
    image: 'String',
    action: 'PageBlocksHeroAction',
  },
  PageBlocksSlideshowItemsAction: {
    callToAction: 'String',
    linkText: 'String',
    link: 'String',
    linkOverride: 'String',
    secondaryText: 'String',
    secondaryLink: 'String',
    secondaryLinkOverride: 'String',
  },
  PageBlocksSlideshowItemsOverlay: {
    image: 'String',
    overlayColor: 'String',
    overlayOpacity: 'String',
  },
  PageBlocksSlideshowItems: {
    title: 'String',
    subTitle: 'String',
    description: 'JSON',
    action: 'PageBlocksSlideshowItemsAction',
    overlay: 'PageBlocksSlideshowItemsOverlay',
  },
  PageBlocksSlideshow: {
    items: 'PageBlocksSlideshowItems',
  },
  PageBlocksComparisonTableItemsMetaA: {
    aOne: 'String',
  },
  PageBlocksComparisonTableItemsMetaB: {
    bOne: 'String',
  },
  PageBlocksComparisonTableItemsMeta: {
    '...on PageBlocksComparisonTableItemsMetaA':
      'PageBlocksComparisonTableItemsMetaA',
    '...on PageBlocksComparisonTableItemsMetaB':
      'PageBlocksComparisonTableItemsMetaB',
  },
  PageBlocksComparisonTableItems: {
    title: 'String',
    subTitle: 'String',
    description: 'JSON',
    bulletPoints: 'String',
    meta: 'PageBlocksComparisonTableItemsMeta',
  },
  PageBlocksComparisonTableAction: {
    callToAction: 'String',
    linkText: 'String',
    link: 'String',
    linkOverride: 'String',
    secondaryText: 'String',
    secondaryLink: 'String',
    secondaryLinkOverride: 'String',
  },
  PageBlocksComparisonTable: {
    title: 'String',
    subTitle: 'String',
    description: 'JSON',
    items: 'PageBlocksComparisonTableItems',
    action: 'PageBlocksComparisonTableAction',
  },
  PageBlocksFeatureFeatures: {
    icon: 'String',
    name: 'String',
    description: 'JSON',
  },
  PageBlocksFeatureOverlay: {
    image: 'String',
    overlayColor: 'String',
    overlayOpacity: 'String',
  },
  PageBlocksFeature: {
    title: 'String',
    subTitle: 'String',
    description: 'JSON',
    featureStyle: 'String',
    features: 'PageBlocksFeatureFeatures',
    overlay: 'PageBlocksFeatureOverlay',
  },
  PageBlocksFullScreenLogoOverlay: {
    image: 'String',
    overlayColor: 'String',
    overlayOpacity: 'String',
  },
  PageBlocksFullScreenLogo: {
    slogan: 'String',
    link: 'String',
    overlay: 'PageBlocksFullScreenLogoOverlay',
  },
  PageBlocksFullScreenHeaderAction: {
    callToAction: 'String',
    linkText: 'String',
    link: 'String',
    linkOverride: 'String',
    secondaryText: 'String',
    secondaryLink: 'String',
    secondaryLinkOverride: 'String',
  },
  PageBlocksFullScreenHeaderOverlay: {
    image: 'String',
    overlayColor: 'String',
    overlayOpacity: 'String',
  },
  PageBlocksFullScreenHeader: {
    title: 'String',
    subTitle: 'String',
    description: 'JSON',
    action: 'PageBlocksFullScreenHeaderAction',
    overlay: 'PageBlocksFullScreenHeaderOverlay',
  },
  PageBlocks: {
    '...on PageBlocksNews': 'PageBlocksNews',
    '...on PageBlocksStatsWithImage': 'PageBlocksStatsWithImage',
    '...on PageBlocksHero': 'PageBlocksHero',
    '...on PageBlocksSlideshow': 'PageBlocksSlideshow',
    '...on PageBlocksComparisonTable': 'PageBlocksComparisonTable',
    '...on PageBlocksFeature': 'PageBlocksFeature',
    '...on PageBlocksFullScreenLogo': 'PageBlocksFullScreenLogo',
    '...on PageBlocksFullScreenHeader': 'PageBlocksFullScreenHeader',
  },
  Page: {
    title: 'String',
    link: 'String',
    seo: 'PageSeo',
    blocks: 'PageBlocks',
    id: 'ID',
    _sys: 'SystemInfo',
    _values: 'JSON',
  },
  PageConnectionEdges: {
    cursor: 'String',
    node: 'Page',
  },
  PageConnection: {
    pageInfo: 'PageInfo',
    totalCount: 'Float',
    edges: 'PageConnectionEdges',
  },
  Mutation: {
    addPendingDocument: 'DocumentNode',
    updateDocument: 'DocumentNode',
    createDocument: 'DocumentNode',
    updateLocaleInfo: 'LocaleInfo',
    createLocaleInfo: 'LocaleInfo',
    updateNews: 'News',
    createNews: 'News',
    updateFooter: 'Footer',
    createFooter: 'Footer',
    updateTheme: 'Theme',
    createTheme: 'Theme',
    updateNavigation: 'Navigation',
    createNavigation: 'Navigation',
    updatePage: 'Page',
    createPage: 'Page',
  },
}
