query DocumentQuery($collection: String!, $relativePath: String!) {
  document(collection: $collection, relativePath: $relativePath) {
    ...PageParts
    ...PostParts
    ...DocumentationParts
    ...AuthorParts
  }
}

query CollectionQuery {
  collections {
    name
    format
  }
}

query MenuQuery {
  collections {
    label
    name
    documents {
      edges {
        node {
          ...on Document {
            _sys {
                filename
              }
            }
          }
        }
      }
    }
}
