query PageQuery {
  ...LayoutQueryFragment
  postsConnection {
    edges {
      node {
        id
        _values
          author {
          ... on Authors {
            ...AuthorsParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

query ContentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  pages(relativePath: $relativePath) {
    ...PagesParts
  }
}

query BlogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  posts(relativePath: $relativePath) {
      ...PostsParts
      author {
        ... on Authors {
            name
            avatar
        }
      }
  }
}
