query getCollections {
  getCollections {
    name
  }
}

query getGlobalDoc {
  getGlobalDocument(relativePath: "index.json") {
    data {
      ...GlobalParts
    }
  }
}

query GetAuthorDocument($path: String!) {
  getAuthorsDocument(relativePath: $path) {
    data {
      ...AuthorsParts
    }
  }
}
