fragment LayoutQueryFragment on Query {
  getGlobalDocument(relativePath: "index.json") {
    data {
      header {
        icon {
          name
          color
          style
        }
        color
        nav {
          href
          label
        }
      }
      footer {
        color
        social {
          facebook
          twitter
          instagram
          github
        }
      }
      theme {
        color
        icon
        font
        darkMode
      }
    }
  }
}
