query GetPost($path: String!) {
  getPostsDocument(relativePath: $path) {
    ...getPostsDocumentParts
  }
}

fragment getPostsDocumentParts on PostsDocument {
  id
  data {
    title
    author {
      __typename
      ... on AuthorsDocument {
        id
        data {
          name
          avatar
        }
      }
    }
    date
    heroImg
    excerpt
    _body
  }
}
