query GetPost($path: String!) {
  getPostsDocument(relativePath: $path) {
    ...getPostsDocumentPartsThisIsATest
  }
}
query getGlobalDoc {
  getPagesDocument(relativePath: "home.md") {
    ...GlobalParts
  }
}

fragment getPostsDocumentPartsThisIsATest on PostsDocument {
  id
  data {
    title
    author {
      __typename
      ... on AuthorsDocument {
        id
        data {
          name
          avatar
        }
      }
    }
    date
    heroImg
    excerpt
    _body
  }
}
