npmAlwaysAuth: false

npmAuthToken: "${NPM_AUTH_TOKEN-must_supply_this_value_in_zshrc}"

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      graphql: ^14.6.0
  "@octokit/rest@16.43.2":
    dependencies:
      "@octokit/core": ^3.3.0
      graphql: ^14.6.0
      subscriptions-transport-ws: ^0.9.18
  "@udecode/plate-csv-serializer@*":
    dependencies:
      slate-history: latest
  "@udecode/plate-mention@*":
    peerDependencies:
      styled-components: latest
  "@udecode/plate@*":
    peerDependencies:
      react-is: ^17.0.2
  create-react-class@*:
    dependencies:
      react: ^16.13.0
  express-graphql@*:
    dependencies:
      graphql: ^14.6.0
  next@9.4.2:
    dependencies:
      typescript: ^4.0.3
  node-fetch@*:
    dependencies:
      encoding: latest
  react-beautiful-dnd@*:
    peerDependencies:
      react-dom: ^16.13.0
  tsup@*:
    dependencies:
      typescript: ^4.0.3

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
