plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

npmAlwaysAuth: false
npmAuthToken: ${NPM_AUTH_TOKEN-must_supply_this_value_in_zshrc}
npmPublishRegistry: "https://registry.npmjs.org"
npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-2.4.2.cjs

packageExtensions:
  '@graphql-codegen/plugin-helpers@*':
    dependencies:
      graphql: ^14.6.0
  '@octokit/rest@16.43.2':
    dependencies:
      '@octokit/core': ^3.3.0
      graphql: ^14.6.0
      subscriptions-transport-ws: ^0.9.18
  react-beautiful-dnd@*:
    peerDependencies:
      react-dom: ^16.13.0
  express-graphql@*:
    dependencies:
      graphql: ^14.6.0
  next@9.4.2:
    dependencies:
      typescript: ^4.0.3
  tsup@*:
    dependencies:
      typescript: ^4.0.3
  create-react-class@*:
    dependencies:
      react: ^16.13.0

  # Plate editor
  '@udecode/plate-csv-serializer@*':
    dependencies:
      slate-history: latest
  "@udecode/plate-mention@*":
    peerDependencies:
      styled-components: latest
  "@udecode/plate@*":
    peerDependencies:
      react-is: ^17.0.2


  # dependencies from needing to build unified-specific packages
  node-fetch@*:
    dependencies:
      encoding: latest
