packages:
    - packages/*
    - packages/@tinacms/*
    - examples/*
    - e2e/*
    - experimental-examples/*
    - playwright/*
catalog:
    "@ariakit/react": ^0.4.15
    "@aws-sdk/client-s3": ^3.744.0
    "@aws-sdk/s3-request-presigner": ^3.744.0
    "@azure/storage-blob": ^12.26.0
    "@biomejs/biome": ^1.9.4
    "@changesets/changelog-github": ^0.5.0
    "@changesets/cli": 2.27.8
    "@clerk/backend": 0.31.3
    "@clerk/clerk-js": 4.56.2
    "@dnd-kit/core": ^6.1.0
    "@dnd-kit/sortable": ^8.0.0
    "@dnd-kit/utilities": ^3.2.2
    "@floating-ui/dom": ^1.6.13
    "@floating-ui/react-dom": ^2.1.2
    "@graphiql/toolkit": 0.8.4
    "@graphql-codegen/core": ^2.6.8
    "@graphql-codegen/typescript": ^4.1.3
    "@graphql-codegen/typescript-operations": ^4.4.1
    "@graphql-codegen/visitor-plugin-common": ^4.1.2
    "@graphql-tools/graphql-file-loader": ^7.5.17
    "@graphql-tools/load": ^7.8.14
    "@graphql-tools/utils": ^10.8.1
    "@iarna/toml": ^2.2.5
    "@monaco-editor/react": 4.7.0-rc.0
    "@octokit/rest": ^22.0.1
    "@playwright/test": ^1.50.1
    "@puppeteer/replay": ^1.3.2
    "@radix-ui/react-checkbox": ^1.1.4
    "@radix-ui/react-dialog": ^1.1.6
    "@radix-ui/react-dropdown-menu": ^2.1.6
    "@radix-ui/react-icons": ^1.3.2
    "@radix-ui/react-popover": ^1.1.15
    "@radix-ui/react-separator": ^1.1.2
    "@radix-ui/react-select": ^2.2.6
    "@radix-ui/react-slot": ^1.1.2
    "@radix-ui/react-toolbar": ^1.1.2
    "@radix-ui/react-tooltip": ^1.2.8
    "@react-hook/window-size": ^3.1.1
    "@rollup/pluginutils": ^5.1.4
    "@sucrase/jest-plugin": ^3.0.0
    "@svgr/core": 8.1.0
    "@svgr/webpack": ^8.1.0
    "@tailwindcss/aspect-ratio": ^0.4.2
    "@tailwindcss/container-queries": ^0.1.1
    "@tailwindcss/typography": ^0.5.16
    "@testing-library/dom": ^10.4.0
    "@testing-library/jest-dom": ^6.7.0
    "@testing-library/react": ^16.2.0
    "@testing-library/user-event": ^14.6.1
    "@types/atob": ^2.1.4
    "@types/clear": 0.1.0
    "@types/cli-spinner": ^0.2.3
    "@types/codemirror": ^5.60.15
    "@types/color-string": ^1.5.5
    "@types/cross-spawn": ^6.0.6
    "@types/express": ^4.17.21
    "@types/figlet": 1.2.0
    "@types/json-diff": ^1.0.3
    "@types/level": ^6.0.3
    "@types/listr": 0.14.2
    "@types/lru-cache": ^5.1.1
    "@types/mdast": ^3.0.15
    "@types/micromatch": ^4.0.9
    "@types/multer": ^1.4.12
    "@types/normalize-path": ^3.0.2
    "@types/picomatch": ^3.0.2
    "@types/prettier": ^2.7.3
    "@types/progress": ^2.0.7
    "@types/prompts": ^2.4.9
    "@types/prop-types": ^15.7.14
    "@types/react-beautiful-dnd": ^13.1.8
    "@types/react-dom": ^18.3.5
    "@types/search-index": ^3.2.4
    "@types/styled-components": ^5.1.34
    "@types/tar": 6.1.13
    "@types/unist": ^2.0.11
    "@types/ws": ^7.4.7
    "@typescript-eslint/eslint-plugin": ^5.62.0
    "@typescript-eslint/parser": ^5.62.0
    "@udecode/cmdk": ^0.2.1
    "@udecode/cn": ^48.0.3
    "@udecode/plate": ^48.0.3
    "@udecode/plate-autoformat": ^48.0.0
    "@udecode/plate-basic-marks": ^48.0.0
    "@udecode/plate-block-quote": ^48
    "@udecode/plate-break": ^48
    "@udecode/plate-code-block": ^48.0.0
    "@udecode/plate-combobox": ^48
    "@udecode/plate-dnd": ^48.0.0
    "@udecode/plate-floating": ^48.0.0
    "@udecode/plate-heading": ^48
    "@udecode/plate-horizontal-rule": ^48
    "@udecode/plate-indent-list": ^48.0.0
    "@udecode/plate-link": ^48.0.0
    "@udecode/plate-list": ^48.0.0
    "@udecode/plate-node-id": ^48.0.0
    "@udecode/plate-reset-node": ^48
    "@udecode/plate-resizable": ^48
    "@udecode/plate-selection": ^48.0.0
    "@udecode/plate-slash-command": ^48.0.0
    "@udecode/plate-table": ^48.0.0
    "@udecode/plate-trailing-block": ^48.0.0
    "@udecode/slate": ^48.0.1
    "@vercel/stega": ^0.0.5
    "@vitejs/plugin-react": 3.1.0
    abstract-level: ^1.0.4
    acorn: 8.8.2
    add: ^2.0.6
    altair-express-middleware: ^7.3.6
    async-lock: ^1.4.1
    auto-bind: ^4.0.0
    autoprefixer: ^10.4.20
    axios: 1.7.5
    body-parser: ^1.20.3
    busboy: ^1.6.0
    c8: ^7.14.0
    ccount: 2.0.1
    chokidar: ^3.6.0
    class-variance-authority: ^0.7.1
    cli-spinner: ^0.2.10
    clipanion: ^3.2.1
    cloudinary: ^1.41.3
    clsx: ^2.1.1
    cmdk: ^1.0.4
    color-string: ^1.9.1
    concat-md: ^0.5.1
    cors: ^2.8.5
    cross-spawn: ^7.0.6
    crypto-js: ^4.2.0
    dotenv: ^16.4.7
    esbuild: ^0.24.2
    estree-util-is-identifier-name: 2.1.0
    fast-glob: ^3.3.3
    final-form: 4.20.10
    final-form-arrays: ^3.1.0
    final-form-set-field-data: ^1.0.2
    fs-extra: ^11.3.0
    glob-parent: ^6.0.2
    graphiql: 3.0.0-alpha.1
    graphql-tag: ^2.12.6
    gray-matter: ^4.0.3
    happy-dom: 15.10.2
    highlight.js: ^11.11.1
    identity-obj-proxy: ^3.0.0
    is-hotkey: ^0.2.0
    isomorphic-git: ^1.29.0
    jest: ^29.7.0
    jest-diff: ^29.7.0
    jest-matcher-utils: ^29.7.0
    js-base64: ^3.7.7
    js-sha1: ^0.6.0
    json-diff: ^1.0.6
    jsonpath-plus: 10.1.0
    chalk: ^5.4.1
    lowlight: ^3.3.0
    lucide-react: ^0.424.0
    many-level: ^2.0.0
    mdast-util-compact: 4.1.1
    mdast-util-directive: 2.2.4
    mdast-util-from-markdown: 1.3.0
    mdast-util-gfm: 2.0.2
    mdast-util-mdx-jsx: 2.1.2
    mdast-util-to-markdown: 1.5.0
    memory-level: ^1.0.0
    micromark-extension-gfm: 2.0.3
    micromark-factory-mdx-expression: 1.0.7
    micromark-factory-space: 1.0.0
    micromark-factory-whitespace: 1.0.0
    micromark-util-character: 1.1.0
    micromark-util-symbol: 1.0.1
    micromark-util-types: 1.0.2
    micromatch: 4.0.8
    minimatch: ^5.1.6
    moment: 2.29.4
    monaco-editor: 0.31.0
    multer: 1.4.5-lts.1
    next-themes: ^0.3.0
    normalize-path: ^3.0.0
    ora: ^8.2.0
    parse-entities: 4.0.1
    picomatch: ^4.0.2
    picomatch-browser: 2.2.6
    postcss-import: ^14.1.0
    postcss-nesting: ^10.2.0
    prettier: ^2.8.8
    pretty-quick: ^3.3.1
    prism-react-renderer: ^2.4.1
    progress: ^2.0.3
    prompts: ^2.4.2
    prop-types: 15.7.2
    puppeteer: ^23.11.1
    query-string: ^9.0.0
    react-beautiful-dnd: ^13.1.1
    react-colorful: ^5.6.1
    react-datetime: ^3.3.1
    react-dnd: ^16.0.1
    react-dnd-html5-backend: ^16.0.1
    react-dropzone: 14.2.3
    react-final-form: ^6.5.9
    react-router-dom: 6.3.0
    react-use: ^17.6.0
    readable-stream: ^4.7.0
    remark: 14.0.2
    remark-gfm: ^2.0.0
    remark-mdx: 2.3.0
    remove: ^0.1.5
    search-index: 4.0.0
    sharp: ^0.33.5
    sqlite-level: ^1.2.1
    stopword: ^3.1.4
    stringify-entities: 4.0.3
    tailwindcss-animate: ^1.0.7
    tar: 7.4.0
    ts-jest: ^29.2.5
    ts-node: ^10.9.2
    tsc-alias: ^1.8.10
    tslib: ^2.8.1
    tsup: ^8.3.6
    turbo: ^2.5.3
    typanion: 3.13.0
    typedoc: ^0.26.11
    typedoc-plugin-markdown: ^3.17.1
    unist-util-source: 4.0.2
    unist-util-stringify-position: 3.0.3
    unist-util-visit: 4.1.2
    url-pattern: ^1.0.3
    uvu: 0.5.6
    validate-npm-package-name: ^7.0.0
    vfile-message: 3.1.4
    webfontloader: 1.6.28
    zod: ^3.24.2
