fragment TestParts on Test {
  ... on TestTem1 {
    foo
  }
  ... on TestTem2 {
    bar
  }
}

fragment PageParts on Page {
  Title
  body
}

fragment PostParts on Post {
  title
  posts {
    __typename
    post {
      ... on Document {
        id
      }
    }
    label
  }
  foo {
    __typename
    bar
  }
  topic
  body
}
