fragment PageParts on Page {
  Title
  body
}

fragment PostParts on Post {
  title
  relatedPosts {
    __typename
    post {
      ... on Document {
        id
      }
    }
    label
  }
  foo {
    __typename
    bar
  }
  topic
  body
}
