fragment PageParts on Page {
  thingOne
  test {
    __typename
    asdf
  }
  Title
  body
}

fragment PostParts on Post {
  title
  posts {
    __typename
    post {
      ... on Document {
        id
      }
    }
  }
  foo {
    __typename
    bar
  }
  topic
  body
}
