query test($relativePath: String!) {
  test(relativePath: $relativePath) {
    ...TestParts
  }
}

query testConnection {
  testConnection {
    totalCount
    edges {
      node {
        ...TestParts
      }
    }
  }
}

query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query pageConnection {
  pageConnection {
    totalCount
    edges {
      node {
        ...PageParts
      }
    }
  }
}

query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    ...PostParts
  }
}

query postConnection {
  postConnection {
    totalCount
    edges {
      node {
        ...PostParts
      }
    }
  }
}
