query DocumentQuery($collection: String!, $relativePath: String!) {
  document(collection: $collection, relativePath: $relativePath) {
    ... on Page {
      ... on PageShowcase {
        title
        items {
          __typename
          title
          description
          image
        }
      }
      ... on PageBlockPage {
        title
        blocks {
          __typename
          ... on PageBlockPageBlocksHero {
            headline
            description
            actions {
              __typename
              label
              url
              variant
            }
          }
          ... on PageBlockPageBlocksFeatures {
            title
            items
          }
          ... on PageBlockPageBlocksCta {
            title
            description
            actions {
              __typename
              label
              url
              variant
            }
          }
        }
      }
    }
    ... on Post {
      title
      author {
        ... on Author {
          name
          bio
          hobbies
          image
        }
        ... on Document {
          id
        }
        ... on Document {
          _internalSys: _sys {
            path
          }
        }
      }
      categories
      body
      image
    }
    ... on Documentation {
      title
      tags {
        __typename
        reference {
          ... on Tag {
            title
            description
          }
          ... on Document {
            id
          }
          ... on Document {
            _internalSys: _sys {
              path
            }
          }
        }
      }
      body
    }
    ... on Author {
      name
      bio
      hobbies
      image
    }
    ... on Document {
      _internalSys: _sys {
        path
      }
    }
  }
}
