query pageQuery {
  ...LayoutQueryFragment
  postConnection {
    edges {
      node {
        id
        _values
        date
        author {
          ... on Author {
            ...AuthorParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query blogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    ...PostParts
    author {
      ... on Author {
        name
        avatar
      }
    }
  }
}

query authorQuery($relativePath: String!) {
  ...LayoutQueryFragment
  author(relativePath: $relativePath) {
    ...AuthorParts
    post {
      edges {
        node {
          id
          title
          excerpt
          date
          _sys {
            filename
          }
        }
      }
    }
  }
}
