fragment PostParts on Post {
  title
  author {
    ... on Document {
      id
    }
  }
  tags
  categories
  published
  featured
  body
}

fragment AuthorParts on Author {
  name
  social {
    __typename
    platform
    handle
  }
  bio
}

fragment BlockPageParts on BlockPage {
  title
  blocks {
    __typename
    ... on BlockPageBlocksHero {
      title
      description
    }
    ... on BlockPageBlocksBlockQuote {
      message
      author {
        ... on Document {
          id
        }
      }
    }
    ... on BlockPageBlocksFeaturedPosts {
      header
      blogs {
        __typename
        item {
          ... on Document {
            id
          }
        }
      }
    }
    ... on BlockPageBlocksFeatureList {
      title
      items {
        __typename
        title
        description
      }
    }
    ... on BlockPageBlocksSlideshow {
      title
      items {
        __typename
        title
        url
      }
    }
  }
}
