query posts($relativePath: String!) {
  posts(relativePath: $relativePath) {
    ...PostsParts
  }
}

query postsConnection {
  postsConnection {
    totalCount
    edges {
      node {
        ...PostsParts
      }
    }
  }
}

query global($relativePath: String!) {
  global(relativePath: $relativePath) {
    ...GlobalParts
  }
}

query globalConnection {
  globalConnection {
    totalCount
    edges {
      node {
        ...GlobalParts
      }
    }
  }
}

query authors($relativePath: String!) {
  authors(relativePath: $relativePath) {
    ...AuthorsParts
  }
}

query authorsConnection {
  authorsConnection {
    totalCount
    edges {
      node {
        ...AuthorsParts
      }
    }
  }
}

query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ...PagesParts
  }
}

query pagesConnection {
  pagesConnection {
    totalCount
    edges {
      node {
        ...PagesParts
      }
    }
  }
}
