//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String'];
  title?: Maybe<Scalars['String']>;
  basename: Scalars['String'];
  breadcrumbs: Array<Scalars['String']>;
  path: Scalars['String'];
  relativePath: Scalars['String'];
  extension: Scalars['String'];
  template: Scalars['String'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean'];
  hasNextPage: Scalars['Boolean'];
  startCursor: Scalars['String'];
  endCursor: Scalars['String'];
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  id: Scalars['ID'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  posts: Posts;
  postsConnection: PostsConnection;
  global: Global;
  globalConnection: GlobalConnection;
  authors: Authors;
  authorsConnection: AuthorsConnection;
  pages: Pages;
  pagesConnection: PagesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryPostsArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryPostsConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<PostsFilter>;
};


export type QueryGlobalArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryGlobalConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<GlobalFilter>;
};


export type QueryAuthorsArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryAuthorsConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<AuthorsFilter>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<PagesFilter>;
};

export type DocumentFilter = {
  posts?: InputMaybe<PostsFilter>;
  global?: InputMaybe<GlobalFilter>;
  authors?: InputMaybe<AuthorsFilter>;
  pages?: InputMaybe<PagesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String'];
  slug: Scalars['String'];
  label?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  format?: Maybe<Scalars['String']>;
  matches?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<DocumentFilter>;
};

export type DocumentNode = Posts | Global | Authors | Pages;

export type PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockc = {
  __typename?: 'PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockc';
  title?: Maybe<Scalars['String']>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock1Items = {
  __typename?: 'PostsPageBlocks3NestedBlocksNestedBlock1Items';
  nestedBlockc?: Maybe<Array<Maybe<PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockc>>>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock1 = PostsPageBlocks3NestedBlocksNestedBlock1Items;

export type PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockc = {
  __typename?: 'PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockc';
  title?: Maybe<Scalars['String']>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock2Items = {
  __typename?: 'PostsPageBlocks3NestedBlocksNestedBlock2Items';
  nestedBlockc?: Maybe<Array<Maybe<PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockc>>>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock2 = PostsPageBlocks3NestedBlocksNestedBlock2Items;

export type PostsPageBlocks3NestedBlocks = {
  __typename?: 'PostsPageBlocks3NestedBlocks';
  nestedBlock1?: Maybe<Array<Maybe<PostsPageBlocks3NestedBlocksNestedBlock1>>>;
  nestedBlock2?: Maybe<Array<Maybe<PostsPageBlocks3NestedBlocksNestedBlock2>>>;
};

export type PostsPageBlocks3 = PostsPageBlocks3NestedBlocks;

export type PostsAuthor = Authors;

export type Posts = Node & Document & {
  __typename?: 'Posts';
  pageBlocks3?: Maybe<Array<Maybe<PostsPageBlocks3>>>;
  title: Scalars['String'];
  heroImg?: Maybe<Scalars['String']>;
  excerpt?: Maybe<Scalars['JSON']>;
  author?: Maybe<PostsAuthor>;
  date?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['JSON']>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockcFilter = {
  title?: InputMaybe<StringFilter>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock1ItemsFilter = {
  nestedBlockc?: InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockcFilter>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock1Filter = {
  items?: InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock1ItemsFilter>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockcFilter = {
  title?: InputMaybe<StringFilter>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock2ItemsFilter = {
  nestedBlockc?: InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockcFilter>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock2Filter = {
  items?: InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock2ItemsFilter>;
};

export type PostsPageBlocks3NestedBlocksFilter = {
  nestedBlock1?: InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock1Filter>;
  nestedBlock2?: InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock2Filter>;
};

export type PostsPageBlocks3Filter = {
  nestedBlocks?: InputMaybe<PostsPageBlocks3NestedBlocksFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
};

export type PostsAuthorFilter = {
  authors?: InputMaybe<AuthorsFilter>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']>;
  before?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
};

export type Posts_BodyDateTimeFilter = {
  format?: InputMaybe<StringFilter>;
};

export type Posts_BodyBlockQuoteFilter = {
  children?: InputMaybe<RichTextFilter>;
  authorName?: InputMaybe<StringFilter>;
};

export type Posts_BodyNewsletterSignupFilter = {
  children?: InputMaybe<RichTextFilter>;
  placeholder?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  disclaimer?: InputMaybe<RichTextFilter>;
};

export type Posts_BodyShortcode1Filter = {
  text?: InputMaybe<StringFilter>;
};

export type Posts_BodyShortcode2Filter = {
  text?: InputMaybe<StringFilter>;
};

export type Posts_BodyFilter = {
  DateTime?: InputMaybe<Posts_BodyDateTimeFilter>;
  BlockQuote?: InputMaybe<Posts_BodyBlockQuoteFilter>;
  NewsletterSignup?: InputMaybe<Posts_BodyNewsletterSignupFilter>;
  Shortcode1?: InputMaybe<Posts_BodyShortcode1Filter>;
  Shortcode2?: InputMaybe<Posts_BodyShortcode2Filter>;
};

export type PostsFilter = {
  pageBlocks3?: InputMaybe<PostsPageBlocks3Filter>;
  title?: InputMaybe<StringFilter>;
  heroImg?: InputMaybe<ImageFilter>;
  excerpt?: InputMaybe<RichTextFilter>;
  author?: InputMaybe<PostsAuthorFilter>;
  date?: InputMaybe<DatetimeFilter>;
  _body?: InputMaybe<Posts_BodyFilter>;
};

export type PostsConnectionEdges = {
  __typename?: 'PostsConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Posts>;
};

export type PostsConnection = Connection & {
  __typename?: 'PostsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<PostsConnectionEdges>>>;
};

export type GlobalHeaderIcon = {
  __typename?: 'GlobalHeaderIcon';
  color?: Maybe<Scalars['String']>;
  style?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
};

export type GlobalHeaderNav = {
  __typename?: 'GlobalHeaderNav';
  href?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
};

export type GlobalHeader = {
  __typename?: 'GlobalHeader';
  icon?: Maybe<GlobalHeaderIcon>;
  color?: Maybe<Scalars['String']>;
  nav?: Maybe<Array<Maybe<GlobalHeaderNav>>>;
};

export type GlobalFooterSocial = {
  __typename?: 'GlobalFooterSocial';
  facebook?: Maybe<Scalars['String']>;
  twitter?: Maybe<Scalars['String']>;
  instagram?: Maybe<Scalars['String']>;
  github?: Maybe<Scalars['String']>;
};

export type GlobalFooter = {
  __typename?: 'GlobalFooter';
  color?: Maybe<Scalars['String']>;
  social?: Maybe<GlobalFooterSocial>;
};

export type GlobalTheme = {
  __typename?: 'GlobalTheme';
  color?: Maybe<Scalars['String']>;
  font?: Maybe<Scalars['String']>;
  icon?: Maybe<Scalars['String']>;
  darkMode?: Maybe<Scalars['String']>;
};

export type Global = Node & Document & {
  __typename?: 'Global';
  header?: Maybe<GlobalHeader>;
  footer?: Maybe<GlobalFooter>;
  theme?: Maybe<GlobalTheme>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type GlobalHeaderIconFilter = {
  color?: InputMaybe<StringFilter>;
  style?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
};

export type GlobalHeaderNavFilter = {
  href?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type GlobalHeaderFilter = {
  icon?: InputMaybe<GlobalHeaderIconFilter>;
  color?: InputMaybe<StringFilter>;
  nav?: InputMaybe<GlobalHeaderNavFilter>;
};

export type GlobalFooterSocialFilter = {
  facebook?: InputMaybe<StringFilter>;
  twitter?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  github?: InputMaybe<StringFilter>;
};

export type GlobalFooterFilter = {
  color?: InputMaybe<StringFilter>;
  social?: InputMaybe<GlobalFooterSocialFilter>;
};

export type GlobalThemeFilter = {
  color?: InputMaybe<StringFilter>;
  font?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  darkMode?: InputMaybe<StringFilter>;
};

export type GlobalFilter = {
  header?: InputMaybe<GlobalHeaderFilter>;
  footer?: InputMaybe<GlobalFooterFilter>;
  theme?: InputMaybe<GlobalThemeFilter>;
};

export type GlobalConnectionEdges = {
  __typename?: 'GlobalConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Global>;
};

export type GlobalConnection = Connection & {
  __typename?: 'GlobalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<GlobalConnectionEdges>>>;
};

export type Authors = Node & Document & {
  __typename?: 'Authors';
  name: Scalars['String'];
  avatar?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type AuthorsFilter = {
  name?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<StringFilter>;
};

export type AuthorsConnectionEdges = {
  __typename?: 'AuthorsConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Authors>;
};

export type AuthorsConnection = Connection & {
  __typename?: 'AuthorsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<AuthorsConnectionEdges>>>;
};

export type PagesBlocksHeroActions = {
  __typename?: 'PagesBlocksHeroActions';
  label?: Maybe<Scalars['String']>;
  type?: Maybe<Scalars['String']>;
  icon?: Maybe<Scalars['Boolean']>;
  link?: Maybe<Scalars['String']>;
};

export type PagesBlocksHeroImage = {
  __typename?: 'PagesBlocksHeroImage';
  src?: Maybe<Scalars['String']>;
  alt?: Maybe<Scalars['String']>;
};

export type PagesBlocksHero = {
  __typename?: 'PagesBlocksHero';
  tagline?: Maybe<Scalars['String']>;
  headline?: Maybe<Scalars['String']>;
  text?: Maybe<Scalars['JSON']>;
  actions?: Maybe<Array<Maybe<PagesBlocksHeroActions>>>;
  image?: Maybe<PagesBlocksHeroImage>;
  color?: Maybe<Scalars['String']>;
};

export type PagesBlocksFeaturesItemsIcon = {
  __typename?: 'PagesBlocksFeaturesItemsIcon';
  color?: Maybe<Scalars['String']>;
  style?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
};

export type PagesBlocksFeaturesItems = {
  __typename?: 'PagesBlocksFeaturesItems';
  icon?: Maybe<PagesBlocksFeaturesItemsIcon>;
  title?: Maybe<Scalars['String']>;
  text?: Maybe<Scalars['String']>;
};

export type PagesBlocksFeatures = {
  __typename?: 'PagesBlocksFeatures';
  items?: Maybe<Array<Maybe<PagesBlocksFeaturesItems>>>;
  color?: Maybe<Scalars['String']>;
};

export type PagesBlocksContent = {
  __typename?: 'PagesBlocksContent';
  body?: Maybe<Scalars['JSON']>;
  color?: Maybe<Scalars['String']>;
};

export type PagesBlocksTestimonial = {
  __typename?: 'PagesBlocksTestimonial';
  quote?: Maybe<Scalars['String']>;
  author?: Maybe<Scalars['String']>;
  color?: Maybe<Scalars['String']>;
};

export type PagesBlocks = PagesBlocksHero | PagesBlocksFeatures | PagesBlocksContent | PagesBlocksTestimonial;

export type Pages = Node & Document & {
  __typename?: 'Pages';
  blocks?: Maybe<Array<Maybe<PagesBlocks>>>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']>;
  exists?: InputMaybe<Scalars['Boolean']>;
};

export type PagesBlocksHeroActionsFilter = {
  label?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  icon?: InputMaybe<BooleanFilter>;
  link?: InputMaybe<StringFilter>;
};

export type PagesBlocksHeroImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type PagesBlocksHeroFilter = {
  tagline?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  text?: InputMaybe<RichTextFilter>;
  actions?: InputMaybe<PagesBlocksHeroActionsFilter>;
  image?: InputMaybe<PagesBlocksHeroImageFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PagesBlocksFeaturesItemsIconFilter = {
  color?: InputMaybe<StringFilter>;
  style?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
};

export type PagesBlocksFeaturesItemsFilter = {
  icon?: InputMaybe<PagesBlocksFeaturesItemsIconFilter>;
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type PagesBlocksFeaturesFilter = {
  items?: InputMaybe<PagesBlocksFeaturesItemsFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PagesBlocksContentFilter = {
  body?: InputMaybe<RichTextFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PagesBlocksTestimonialFilter = {
  quote?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PagesBlocksFilter = {
  hero?: InputMaybe<PagesBlocksHeroFilter>;
  features?: InputMaybe<PagesBlocksFeaturesFilter>;
  content?: InputMaybe<PagesBlocksContentFilter>;
  testimonial?: InputMaybe<PagesBlocksTestimonialFilter>;
};

export type PagesFilter = {
  blocks?: InputMaybe<PagesBlocksFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updatePosts: Posts;
  createPosts: Posts;
  updateGlobal: Global;
  createGlobal: Global;
  updateAuthors: Authors;
  createAuthors: Authors;
  updatePages: Pages;
  createPages: Pages;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String'];
  relativePath: Scalars['String'];
  template?: InputMaybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationUpdatePostsArgs = {
  relativePath: Scalars['String'];
  params: PostsMutation;
};


export type MutationCreatePostsArgs = {
  relativePath: Scalars['String'];
  params: PostsMutation;
};


export type MutationUpdateGlobalArgs = {
  relativePath: Scalars['String'];
  params: GlobalMutation;
};


export type MutationCreateGlobalArgs = {
  relativePath: Scalars['String'];
  params: GlobalMutation;
};


export type MutationUpdateAuthorsArgs = {
  relativePath: Scalars['String'];
  params: AuthorsMutation;
};


export type MutationCreateAuthorsArgs = {
  relativePath: Scalars['String'];
  params: AuthorsMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String'];
  params: PagesMutation;
};

export type DocumentUpdateMutation = {
  posts?: InputMaybe<PostsMutation>;
  global?: InputMaybe<GlobalMutation>;
  authors?: InputMaybe<AuthorsMutation>;
  pages?: InputMaybe<PagesMutation>;
  relativePath?: InputMaybe<Scalars['String']>;
};

export type DocumentMutation = {
  posts?: InputMaybe<PostsMutation>;
  global?: InputMaybe<GlobalMutation>;
  authors?: InputMaybe<AuthorsMutation>;
  pages?: InputMaybe<PagesMutation>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockcMutation = {
  title?: InputMaybe<Scalars['String']>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock1ItemsMutation = {
  nestedBlockc?: InputMaybe<Array<InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockcMutation>>>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock1Mutation = {
  items?: InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock1ItemsMutation>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockcMutation = {
  title?: InputMaybe<Scalars['String']>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock2ItemsMutation = {
  nestedBlockc?: InputMaybe<Array<InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockcMutation>>>;
};

export type PostsPageBlocks3NestedBlocksNestedBlock2Mutation = {
  items?: InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock2ItemsMutation>;
};

export type PostsPageBlocks3NestedBlocksMutation = {
  nestedBlock1?: InputMaybe<Array<InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock1Mutation>>>;
  nestedBlock2?: InputMaybe<Array<InputMaybe<PostsPageBlocks3NestedBlocksNestedBlock2Mutation>>>;
};

export type PostsPageBlocks3Mutation = {
  nestedBlocks?: InputMaybe<PostsPageBlocks3NestedBlocksMutation>;
};

export type PostsMutation = {
  pageBlocks3?: InputMaybe<Array<InputMaybe<PostsPageBlocks3Mutation>>>;
  title?: InputMaybe<Scalars['String']>;
  heroImg?: InputMaybe<Scalars['String']>;
  excerpt?: InputMaybe<Scalars['JSON']>;
  author?: InputMaybe<Scalars['String']>;
  date?: InputMaybe<Scalars['String']>;
  _body?: InputMaybe<Scalars['JSON']>;
};

export type GlobalHeaderIconMutation = {
  color?: InputMaybe<Scalars['String']>;
  style?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
};

export type GlobalHeaderNavMutation = {
  href?: InputMaybe<Scalars['String']>;
  label?: InputMaybe<Scalars['String']>;
};

export type GlobalHeaderMutation = {
  icon?: InputMaybe<GlobalHeaderIconMutation>;
  color?: InputMaybe<Scalars['String']>;
  nav?: InputMaybe<Array<InputMaybe<GlobalHeaderNavMutation>>>;
};

export type GlobalFooterSocialMutation = {
  facebook?: InputMaybe<Scalars['String']>;
  twitter?: InputMaybe<Scalars['String']>;
  instagram?: InputMaybe<Scalars['String']>;
  github?: InputMaybe<Scalars['String']>;
};

export type GlobalFooterMutation = {
  color?: InputMaybe<Scalars['String']>;
  social?: InputMaybe<GlobalFooterSocialMutation>;
};

export type GlobalThemeMutation = {
  color?: InputMaybe<Scalars['String']>;
  font?: InputMaybe<Scalars['String']>;
  icon?: InputMaybe<Scalars['String']>;
  darkMode?: InputMaybe<Scalars['String']>;
};

export type GlobalMutation = {
  header?: InputMaybe<GlobalHeaderMutation>;
  footer?: InputMaybe<GlobalFooterMutation>;
  theme?: InputMaybe<GlobalThemeMutation>;
};

export type AuthorsMutation = {
  name?: InputMaybe<Scalars['String']>;
  avatar?: InputMaybe<Scalars['String']>;
};

export type PagesBlocksHeroActionsMutation = {
  label?: InputMaybe<Scalars['String']>;
  type?: InputMaybe<Scalars['String']>;
  icon?: InputMaybe<Scalars['Boolean']>;
  link?: InputMaybe<Scalars['String']>;
};

export type PagesBlocksHeroImageMutation = {
  src?: InputMaybe<Scalars['String']>;
  alt?: InputMaybe<Scalars['String']>;
};

export type PagesBlocksHeroMutation = {
  tagline?: InputMaybe<Scalars['String']>;
  headline?: InputMaybe<Scalars['String']>;
  text?: InputMaybe<Scalars['JSON']>;
  actions?: InputMaybe<Array<InputMaybe<PagesBlocksHeroActionsMutation>>>;
  image?: InputMaybe<PagesBlocksHeroImageMutation>;
  color?: InputMaybe<Scalars['String']>;
};

export type PagesBlocksFeaturesItemsIconMutation = {
  color?: InputMaybe<Scalars['String']>;
  style?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
};

export type PagesBlocksFeaturesItemsMutation = {
  icon?: InputMaybe<PagesBlocksFeaturesItemsIconMutation>;
  title?: InputMaybe<Scalars['String']>;
  text?: InputMaybe<Scalars['String']>;
};

export type PagesBlocksFeaturesMutation = {
  items?: InputMaybe<Array<InputMaybe<PagesBlocksFeaturesItemsMutation>>>;
  color?: InputMaybe<Scalars['String']>;
};

export type PagesBlocksContentMutation = {
  body?: InputMaybe<Scalars['JSON']>;
  color?: InputMaybe<Scalars['String']>;
};

export type PagesBlocksTestimonialMutation = {
  quote?: InputMaybe<Scalars['String']>;
  author?: InputMaybe<Scalars['String']>;
  color?: InputMaybe<Scalars['String']>;
};

export type PagesBlocksMutation = {
  hero?: InputMaybe<PagesBlocksHeroMutation>;
  features?: InputMaybe<PagesBlocksFeaturesMutation>;
  content?: InputMaybe<PagesBlocksContentMutation>;
  testimonial?: InputMaybe<PagesBlocksTestimonialMutation>;
};

export type PagesMutation = {
  blocks?: InputMaybe<Array<InputMaybe<PagesBlocksMutation>>>;
};

export type LayoutQueryFragmentFragment = { __typename?: 'Query', global: { __typename?: 'Global', header?: { __typename: 'GlobalHeader', color?: string | null, icon?: { __typename: 'GlobalHeaderIcon', color?: string | null, style?: string | null, name?: string | null } | null, nav?: Array<{ __typename: 'GlobalHeaderNav', href?: string | null, label?: string | null } | null> | null } | null, footer?: { __typename: 'GlobalFooter', color?: string | null, social?: { __typename: 'GlobalFooterSocial', facebook?: string | null, twitter?: string | null, instagram?: string | null, github?: string | null } | null } | null, theme?: { __typename: 'GlobalTheme', color?: string | null, font?: string | null, icon?: string | null, darkMode?: string | null } | null } };

export type PageQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type PageQueryQuery = { __typename?: 'Query', postsConnection: { __typename?: 'PostsConnection', edges?: Array<{ __typename?: 'PostsConnectionEdges', node?: { __typename?: 'Posts', id: string, title: string, heroImg?: string | null, excerpt?: any | null, date?: string | null, _body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string }, pageBlocks3?: Array<{ __typename: 'PostsPageBlocks3NestedBlocks', nestedBlock1?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock1Items', nestedBlockc?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockc', title?: string | null } | null> | null } | null> | null, nestedBlock2?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock2Items', nestedBlockc?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockc', title?: string | null } | null> | null } | null> | null } | null> | null, author?: { __typename?: 'Authors', name: string, avatar?: string | null, id: string } | null } | null } | null> | null }, global: { __typename?: 'Global', header?: { __typename: 'GlobalHeader', color?: string | null, icon?: { __typename: 'GlobalHeaderIcon', color?: string | null, style?: string | null, name?: string | null } | null, nav?: Array<{ __typename: 'GlobalHeaderNav', href?: string | null, label?: string | null } | null> | null } | null, footer?: { __typename: 'GlobalFooter', color?: string | null, social?: { __typename: 'GlobalFooterSocial', facebook?: string | null, twitter?: string | null, instagram?: string | null, github?: string | null } | null } | null, theme?: { __typename: 'GlobalTheme', color?: string | null, font?: string | null, icon?: string | null, darkMode?: string | null } | null } };

export type ContentQueryQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type ContentQueryQuery = { __typename?: 'Query', pages: { __typename?: 'Pages', blocks?: Array<{ __typename: 'PagesBlocksHero', tagline?: string | null, headline?: string | null, text?: any | null, color?: string | null, actions?: Array<{ __typename: 'PagesBlocksHeroActions', label?: string | null, type?: string | null, icon?: boolean | null, link?: string | null } | null> | null, image?: { __typename: 'PagesBlocksHeroImage', src?: string | null, alt?: string | null } | null } | { __typename: 'PagesBlocksFeatures', color?: string | null, items?: Array<{ __typename: 'PagesBlocksFeaturesItems', title?: string | null, text?: string | null, icon?: { __typename: 'PagesBlocksFeaturesItemsIcon', color?: string | null, style?: string | null, name?: string | null } | null } | null> | null } | { __typename: 'PagesBlocksContent', body?: any | null, color?: string | null } | { __typename: 'PagesBlocksTestimonial', quote?: string | null, author?: string | null, color?: string | null } | null> | null }, global: { __typename?: 'Global', header?: { __typename: 'GlobalHeader', color?: string | null, icon?: { __typename: 'GlobalHeaderIcon', color?: string | null, style?: string | null, name?: string | null } | null, nav?: Array<{ __typename: 'GlobalHeaderNav', href?: string | null, label?: string | null } | null> | null } | null, footer?: { __typename: 'GlobalFooter', color?: string | null, social?: { __typename: 'GlobalFooterSocial', facebook?: string | null, twitter?: string | null, instagram?: string | null, github?: string | null } | null } | null, theme?: { __typename: 'GlobalTheme', color?: string | null, font?: string | null, icon?: string | null, darkMode?: string | null } | null } };

export type BlogPostQueryQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type BlogPostQueryQuery = { __typename?: 'Query', posts: { __typename?: 'Posts', title: string, heroImg?: string | null, excerpt?: any | null, date?: string | null, _body?: any | null, author?: { __typename?: 'Authors', name: string, avatar?: string | null, id: string } | null, pageBlocks3?: Array<{ __typename: 'PostsPageBlocks3NestedBlocks', nestedBlock1?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock1Items', nestedBlockc?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockc', title?: string | null } | null> | null } | null> | null, nestedBlock2?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock2Items', nestedBlockc?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockc', title?: string | null } | null> | null } | null> | null } | null> | null }, global: { __typename?: 'Global', header?: { __typename: 'GlobalHeader', color?: string | null, icon?: { __typename: 'GlobalHeaderIcon', color?: string | null, style?: string | null, name?: string | null } | null, nav?: Array<{ __typename: 'GlobalHeaderNav', href?: string | null, label?: string | null } | null> | null } | null, footer?: { __typename: 'GlobalFooter', color?: string | null, social?: { __typename: 'GlobalFooterSocial', facebook?: string | null, twitter?: string | null, instagram?: string | null, github?: string | null } | null } | null, theme?: { __typename: 'GlobalTheme', color?: string | null, font?: string | null, icon?: string | null, darkMode?: string | null } | null } };

export type PostsPartsFragment = { __typename?: 'Posts', title: string, heroImg?: string | null, excerpt?: any | null, date?: string | null, _body?: any | null, pageBlocks3?: Array<{ __typename: 'PostsPageBlocks3NestedBlocks', nestedBlock1?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock1Items', nestedBlockc?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockc', title?: string | null } | null> | null } | null> | null, nestedBlock2?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock2Items', nestedBlockc?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockc', title?: string | null } | null> | null } | null> | null } | null> | null, author?: { __typename?: 'Authors', name: string, avatar?: string | null, id: string } | null };

export type GlobalPartsFragment = { __typename?: 'Global', header?: { __typename: 'GlobalHeader', color?: string | null, icon?: { __typename: 'GlobalHeaderIcon', color?: string | null, style?: string | null, name?: string | null } | null, nav?: Array<{ __typename: 'GlobalHeaderNav', href?: string | null, label?: string | null } | null> | null } | null, footer?: { __typename: 'GlobalFooter', color?: string | null, social?: { __typename: 'GlobalFooterSocial', facebook?: string | null, twitter?: string | null, instagram?: string | null, github?: string | null } | null } | null, theme?: { __typename: 'GlobalTheme', color?: string | null, font?: string | null, icon?: string | null, darkMode?: string | null } | null };

export type AuthorsPartsFragment = { __typename?: 'Authors', name: string, avatar?: string | null };

export type PagesPartsFragment = { __typename?: 'Pages', blocks?: Array<{ __typename: 'PagesBlocksHero', tagline?: string | null, headline?: string | null, text?: any | null, color?: string | null, actions?: Array<{ __typename: 'PagesBlocksHeroActions', label?: string | null, type?: string | null, icon?: boolean | null, link?: string | null } | null> | null, image?: { __typename: 'PagesBlocksHeroImage', src?: string | null, alt?: string | null } | null } | { __typename: 'PagesBlocksFeatures', color?: string | null, items?: Array<{ __typename: 'PagesBlocksFeaturesItems', title?: string | null, text?: string | null, icon?: { __typename: 'PagesBlocksFeaturesItemsIcon', color?: string | null, style?: string | null, name?: string | null } | null } | null> | null } | { __typename: 'PagesBlocksContent', body?: any | null, color?: string | null } | { __typename: 'PagesBlocksTestimonial', quote?: string | null, author?: string | null, color?: string | null } | null> | null };

export type PostsQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type PostsQuery = { __typename?: 'Query', posts: { __typename?: 'Posts', id: string, title: string, heroImg?: string | null, excerpt?: any | null, date?: string | null, _body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, pageBlocks3?: Array<{ __typename: 'PostsPageBlocks3NestedBlocks', nestedBlock1?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock1Items', nestedBlockc?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockc', title?: string | null } | null> | null } | null> | null, nestedBlock2?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock2Items', nestedBlockc?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockc', title?: string | null } | null> | null } | null> | null } | null> | null, author?: { __typename?: 'Authors', name: string, avatar?: string | null, id: string } | null } };

export type PostsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<PostsFilter>;
}>;


export type PostsConnectionQuery = { __typename?: 'Query', postsConnection: { __typename?: 'PostsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostsConnectionEdges', cursor: string, node?: { __typename?: 'Posts', id: string, title: string, heroImg?: string | null, excerpt?: any | null, date?: string | null, _body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, pageBlocks3?: Array<{ __typename: 'PostsPageBlocks3NestedBlocks', nestedBlock1?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock1Items', nestedBlockc?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock1ItemsNestedBlockc', title?: string | null } | null> | null } | null> | null, nestedBlock2?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock2Items', nestedBlockc?: Array<{ __typename: 'PostsPageBlocks3NestedBlocksNestedBlock2ItemsNestedBlockc', title?: string | null } | null> | null } | null> | null } | null> | null, author?: { __typename?: 'Authors', name: string, avatar?: string | null, id: string } | null } | null } | null> | null } };

export type GlobalQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type GlobalQuery = { __typename?: 'Query', global: { __typename?: 'Global', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, header?: { __typename: 'GlobalHeader', color?: string | null, icon?: { __typename: 'GlobalHeaderIcon', color?: string | null, style?: string | null, name?: string | null } | null, nav?: Array<{ __typename: 'GlobalHeaderNav', href?: string | null, label?: string | null } | null> | null } | null, footer?: { __typename: 'GlobalFooter', color?: string | null, social?: { __typename: 'GlobalFooterSocial', facebook?: string | null, twitter?: string | null, instagram?: string | null, github?: string | null } | null } | null, theme?: { __typename: 'GlobalTheme', color?: string | null, font?: string | null, icon?: string | null, darkMode?: string | null } | null } };

export type GlobalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<GlobalFilter>;
}>;


export type GlobalConnectionQuery = { __typename?: 'Query', globalConnection: { __typename?: 'GlobalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlobalConnectionEdges', cursor: string, node?: { __typename?: 'Global', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, header?: { __typename: 'GlobalHeader', color?: string | null, icon?: { __typename: 'GlobalHeaderIcon', color?: string | null, style?: string | null, name?: string | null } | null, nav?: Array<{ __typename: 'GlobalHeaderNav', href?: string | null, label?: string | null } | null> | null } | null, footer?: { __typename: 'GlobalFooter', color?: string | null, social?: { __typename: 'GlobalFooterSocial', facebook?: string | null, twitter?: string | null, instagram?: string | null, github?: string | null } | null } | null, theme?: { __typename: 'GlobalTheme', color?: string | null, font?: string | null, icon?: string | null, darkMode?: string | null } | null } | null } | null> | null } };

export type AuthorsQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type AuthorsQuery = { __typename?: 'Query', authors: { __typename?: 'Authors', id: string, name: string, avatar?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AuthorsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<AuthorsFilter>;
}>;


export type AuthorsConnectionQuery = { __typename?: 'Query', authorsConnection: { __typename?: 'AuthorsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AuthorsConnectionEdges', cursor: string, node?: { __typename?: 'Authors', id: string, name: string, avatar?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PagesQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type PagesQuery = { __typename?: 'Query', pages: { __typename?: 'Pages', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'PagesBlocksHero', tagline?: string | null, headline?: string | null, text?: any | null, color?: string | null, actions?: Array<{ __typename: 'PagesBlocksHeroActions', label?: string | null, type?: string | null, icon?: boolean | null, link?: string | null } | null> | null, image?: { __typename: 'PagesBlocksHeroImage', src?: string | null, alt?: string | null } | null } | { __typename: 'PagesBlocksFeatures', color?: string | null, items?: Array<{ __typename: 'PagesBlocksFeaturesItems', title?: string | null, text?: string | null, icon?: { __typename: 'PagesBlocksFeaturesItemsIcon', color?: string | null, style?: string | null, name?: string | null } | null } | null> | null } | { __typename: 'PagesBlocksContent', body?: any | null, color?: string | null } | { __typename: 'PagesBlocksTestimonial', quote?: string | null, author?: string | null, color?: string | null } | null> | null } };

export type PagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<PagesFilter>;
}>;


export type PagesConnectionQuery = { __typename?: 'Query', pagesConnection: { __typename?: 'PagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PagesConnectionEdges', cursor: string, node?: { __typename?: 'Pages', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'PagesBlocksHero', tagline?: string | null, headline?: string | null, text?: any | null, color?: string | null, actions?: Array<{ __typename: 'PagesBlocksHeroActions', label?: string | null, type?: string | null, icon?: boolean | null, link?: string | null } | null> | null, image?: { __typename: 'PagesBlocksHeroImage', src?: string | null, alt?: string | null } | null } | { __typename: 'PagesBlocksFeatures', color?: string | null, items?: Array<{ __typename: 'PagesBlocksFeaturesItems', title?: string | null, text?: string | null, icon?: { __typename: 'PagesBlocksFeaturesItemsIcon', color?: string | null, style?: string | null, name?: string | null } | null } | null> | null } | { __typename: 'PagesBlocksContent', body?: any | null, color?: string | null } | { __typename: 'PagesBlocksTestimonial', quote?: string | null, author?: string | null, color?: string | null } | null> | null } | null } | null> | null } };

export const GlobalPartsFragmentDoc = gql`
    fragment GlobalParts on Global {
  header {
    __typename
    icon {
      __typename
      color
      style
      name
    }
    color
    nav {
      __typename
      href
      label
    }
  }
  footer {
    __typename
    color
    social {
      __typename
      facebook
      twitter
      instagram
      github
    }
  }
  theme {
    __typename
    color
    font
    icon
    darkMode
  }
}
    `;
export const LayoutQueryFragmentFragmentDoc = gql`
    fragment LayoutQueryFragment on Query {
  global(relativePath: "index.json") {
    ...GlobalParts
  }
}
    ${GlobalPartsFragmentDoc}`;
export const PostsPartsFragmentDoc = gql`
    fragment PostsParts on Posts {
  pageBlocks3 {
    __typename
    ... on PostsPageBlocks3NestedBlocks {
      nestedBlock1 {
        __typename
        ... on PostsPageBlocks3NestedBlocksNestedBlock1Items {
          nestedBlockc {
            __typename
            title
          }
        }
      }
      nestedBlock2 {
        __typename
        ... on PostsPageBlocks3NestedBlocksNestedBlock2Items {
          nestedBlockc {
            __typename
            title
          }
        }
      }
    }
  }
  title
  heroImg
  excerpt
  author {
    ... on Authors {
      name
      avatar
    }
    ... on Document {
      id
    }
  }
  date
  _body
}
    `;
export const AuthorsPartsFragmentDoc = gql`
    fragment AuthorsParts on Authors {
  name
  avatar
}
    `;
export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  blocks {
    __typename
    ... on PagesBlocksHero {
      tagline
      headline
      text
      actions {
        __typename
        label
        type
        icon
        link
      }
      image {
        __typename
        src
        alt
      }
      color
    }
    ... on PagesBlocksFeatures {
      items {
        __typename
        icon {
          __typename
          color
          style
          name
        }
        title
        text
      }
      color
    }
    ... on PagesBlocksContent {
      body
      color
    }
    ... on PagesBlocksTestimonial {
      quote
      author
      color
    }
  }
}
    `;
export const PageQueryDocument = gql`
    query PageQuery {
  ...LayoutQueryFragment
  postsConnection {
    edges {
      node {
        id
        ...PostsParts
        _sys {
          filename
        }
      }
    }
  }
}
    ${LayoutQueryFragmentFragmentDoc}
${PostsPartsFragmentDoc}`;
export const ContentQueryDocument = gql`
    query ContentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  pages(relativePath: $relativePath) {
    ...PagesParts
  }
}
    ${LayoutQueryFragmentFragmentDoc}
${PagesPartsFragmentDoc}`;
export const BlogPostQueryDocument = gql`
    query BlogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  posts(relativePath: $relativePath) {
    ...PostsParts
    author {
      ... on Authors {
        name
        avatar
      }
    }
  }
}
    ${LayoutQueryFragmentFragmentDoc}
${PostsPartsFragmentDoc}`;
export const PostsDocument = gql`
    query posts($relativePath: String!) {
  posts(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostsParts
  }
}
    ${PostsPartsFragmentDoc}`;
export const PostsConnectionDocument = gql`
    query postsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostsFilter) {
  postsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostsParts
      }
    }
  }
}
    ${PostsPartsFragmentDoc}`;
export const GlobalDocument = gql`
    query global($relativePath: String!) {
  global(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalParts
  }
}
    ${GlobalPartsFragmentDoc}`;
export const GlobalConnectionDocument = gql`
    query globalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalFilter) {
  globalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalParts
      }
    }
  }
}
    ${GlobalPartsFragmentDoc}`;
export const AuthorsDocument = gql`
    query authors($relativePath: String!) {
  authors(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AuthorsParts
  }
}
    ${AuthorsPartsFragmentDoc}`;
export const AuthorsConnectionDocument = gql`
    query authorsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AuthorsFilter) {
  authorsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AuthorsParts
      }
    }
  }
}
    ${AuthorsPartsFragmentDoc}`;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      PageQuery(variables?: PageQueryQueryVariables, options?: C): Promise<{data: PageQueryQuery, variables: PageQueryQueryVariables, query: string}> {
        return requester<{data: PageQueryQuery, variables: PageQueryQueryVariables, query: string}, PageQueryQueryVariables>(PageQueryDocument, variables, options);
      },
    ContentQuery(variables: ContentQueryQueryVariables, options?: C): Promise<{data: ContentQueryQuery, variables: ContentQueryQueryVariables, query: string}> {
        return requester<{data: ContentQueryQuery, variables: ContentQueryQueryVariables, query: string}, ContentQueryQueryVariables>(ContentQueryDocument, variables, options);
      },
    BlogPostQuery(variables: BlogPostQueryQueryVariables, options?: C): Promise<{data: BlogPostQueryQuery, variables: BlogPostQueryQueryVariables, query: string}> {
        return requester<{data: BlogPostQueryQuery, variables: BlogPostQueryQueryVariables, query: string}, BlogPostQueryQueryVariables>(BlogPostQueryDocument, variables, options);
      },
    posts(variables: PostsQueryVariables, options?: C): Promise<{data: PostsQuery, variables: PostsQueryVariables, query: string}> {
        return requester<{data: PostsQuery, variables: PostsQueryVariables, query: string}, PostsQueryVariables>(PostsDocument, variables, options);
      },
    postsConnection(variables?: PostsConnectionQueryVariables, options?: C): Promise<{data: PostsConnectionQuery, variables: PostsConnectionQueryVariables, query: string}> {
        return requester<{data: PostsConnectionQuery, variables: PostsConnectionQueryVariables, query: string}, PostsConnectionQueryVariables>(PostsConnectionDocument, variables, options);
      },
    global(variables: GlobalQueryVariables, options?: C): Promise<{data: GlobalQuery, variables: GlobalQueryVariables, query: string}> {
        return requester<{data: GlobalQuery, variables: GlobalQueryVariables, query: string}, GlobalQueryVariables>(GlobalDocument, variables, options);
      },
    globalConnection(variables?: GlobalConnectionQueryVariables, options?: C): Promise<{data: GlobalConnectionQuery, variables: GlobalConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalConnectionQuery, variables: GlobalConnectionQueryVariables, query: string}, GlobalConnectionQueryVariables>(GlobalConnectionDocument, variables, options);
      },
    authors(variables: AuthorsQueryVariables, options?: C): Promise<{data: AuthorsQuery, variables: AuthorsQueryVariables, query: string}> {
        return requester<{data: AuthorsQuery, variables: AuthorsQueryVariables, query: string}, AuthorsQueryVariables>(AuthorsDocument, variables, options);
      },
    authorsConnection(variables?: AuthorsConnectionQueryVariables, options?: C): Promise<{data: AuthorsConnectionQuery, variables: AuthorsConnectionQueryVariables, query: string}> {
        return requester<{data: AuthorsConnectionQuery, variables: AuthorsConnectionQueryVariables, query: string}, AuthorsConnectionQueryVariables>(AuthorsConnectionDocument, variables, options);
      },
    pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (client: TinaClient) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: any,
    client
  ) => Promise<any> = async (doc, vars, _options) => {
    const data = await client.request({
      query: doc,
      variables: vars,
    });

    return { data: data?.data, query: doc, variables: vars || {} };
  };

  return requester;
};

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(createClient({ url: "http://localhost:4001/graphql", queries }))
  );

export const queries = (client: TinaClient) => {
  const requester = generateRequester(client);
  return getSdk(requester);
};

  