---
label: default
hide_body: false
fields:
  - type: text
    label: Title
    name: title
    description: Used for SEO. Fallback for Headline.
    config:
      required: true
  - type: text
    name: headline
    label: Page Headline
    description: Optional override for title
  - type: datetime
    label: Date
    name: date
    description: Date is seen by user
    config:
      required: true
    default: now
  - type: datetime
    name: publishdate
    label: Publish Date
    description: Date this page should be made public
    config:
      date_format: MMMM DD, YYYY
      time_format: h:mm A
      required: true
    default: now
  - type: datetime
    name: expirydate
    label: Expiry Date
    description: Date this page should be unpublished
    config:
      date_format: MMMM DD, YYYY
      time_format: h:mmA
    default: '2030-01-01T04:00:00.000+00:00'
  - type: textarea
    name: description
    label: Description
    description: Used for SEO
    config:
      required: false
  - type: textarea
    name: textline
    label: Page Textline
    description: Optional override for description
  - type: image_gallery
    name: images
    label: Images
    description: Used for SEO & Featured Images
  - name: photo_credit
    type: text
    config:
      required: false
    label: Photo Credit
    description: Credit to appear with header image
  - type: list
    name: authors
    label: Authors
    config:
      use_select: true
      source:
        type: documents
        file: hugo/data/authors.yml
        path: map
        section: authors
    default: []
  - type: list
    name: categories
    label: Categories
    config:
      use_select: true
      source:
        type: simple
      options:
        - CMS
        - Jekyll
        - Hugo
        - Static Sites
        - Static Site Generators
        - Company
        - Frontend-Friday
        - Beyond Static
        - VuePress
        - Engineering
  - type: tag_list
    name: tags
    label: Tags
  - type: field_group
    label: Footer Call To Action
    name: cta
    description: Configure the CTA in the page's footer
    fields:
      - type: text
        name: headline
        label: Headline
        description: Optional; defaults will be used if empty
      - type: textarea
        name: textline
        label: Textline
        description: Optional; defaults will be used if empty
      - type: field_group_list
        name: calls_to_action
        label: Calls to Action
        description: Configure buttons/links in the CTA
        fields:
          - type: text
            label: Permalink
            name: permalink
            config:
              required: true
          - type: text
            name: textline
            label: Textline
            hidden: false
            config:
              required: true
          - type: boolean
            name: button
            label: Is button?
        config:
          labelField: textline
  - type: boolean
    name: private
    label: Exclude from sitemap?
  - type: number
    name: weight
    label: Weight
    description: Used to handle sorting order, menu order, etc.
  - type: list
    name: aliases
    label: Aliases
    description: Create page redirects. Put in relative path
    config:
      use_select: false
      source:
        type: datafiles
  - type: list
    name: menu
    label: menu
pages:
  - hugo/content/blog/3-patterns-for-loading-data-with-react.md
  - hugo/content/blog/3-tips-for-mastering-blocks.md
  - hugo/content/blog/5-options-for-automating-your-software-deployments.md
  - hugo/content/blog/5-ways-to-handle-forms-on-your-static-site.md
  - hugo/content/blog/Introducing-Custom-Build-Commands.md
  - hugo/content/blog/Using-JSON-Configuration-With-VuePress.md
  - hugo/content/blog/_index.md
  - hugo/content/blog/a-hugo-update-everyone-should-be-talking-about.md
  - hugo/content/blog/add-functionality-to-your-hugo-site-with-theme-components.md
  - hugo/content/blog/adding-dns-and-edge-functions-to-our-cloudformation-stack.md
  - hugo/content/blog/an-introduction-to-theming-in-vuepress.md
  - hugo/content/blog/announcing-tina-an-open-source-site-editor.md
  - hugo/content/blog/automate-your-static-hosting-environment-with-aws-cloudformation.md
  - hugo/content/blog/better-content-management-for-gatsby.md
  - hugo/content/blog/big-improvements-to-front-matter-templates.md
  - hugo/content/blog/bigger-better-editor.md
  - hugo/content/blog/block-labels-read-only-docs-and-more.md
  - hugo/content/blog/build-a-json-api-with-hugo.md
  - hugo/content/blog/building-a-company-component-library.md
  - hugo/content/blog/choose-static.md
  - hugo/content/blog/cloudinary-integration.md
  - hugo/content/blog/create-in-app-documentation-for-content-editors.md
  - hugo/content/blog/creating-a-multilingual-blog-with-jekyll.md
  - hugo/content/blog/custom-configuration-for-data-files.md
  - hugo/content/blog/customize-sidebar-and-assign-front-matter-templates.md
  - hugo/content/blog/data-files-directories-and-duplicating-pages.md
  - hugo/content/blog/data-relationships-in-hugo.md
  - hugo/content/blog/demystifying-hugo-conditionals.md
  - hugo/content/blog/discontinuing-wysiwyg-editor-new-focus-on-markdown.md
  - hugo/content/blog/discontinuing-zip-sites.md
  - hugo/content/blog/for-static-sites-theres-no-excuse-not-to-use-a-cdn.md
  - hugo/content/blog/forestry-git-backed-content-management-for-gatsby.md
  - hugo/content/blog/forestry-gitlab.md
  - hugo/content/blog/forestry-io-at-jamstack-conf-san-francisco-oct-16-18.md
  - hugo/content/blog/forestryio-techstars-2016.md
  - hugo/content/blog/form-builder-with-formspree-forestry-blocks.md
  - hugo/content/blog/front-matter-templates.md
  - hugo/content/blog/ftp-an-outdated-deployment-method-for-static-sites.md
  - hugo/content/blog/full-speed-ahead-in-2019.md
  - hugo/content/blog/full-text-searching-with-postgres.md
  - hugo/content/blog/gulp-and-webpack-best-of-both-worlds.md
  - hugo/content/blog/harness-the-power-of-static-to-create-presentations.md
  - hugo/content/blog/how-i-reduced-my-jekyll-build-time-by-61.md
  - hugo/content/blog/how-to-use-hugo-s-image-processing-with-forestry.md
  - hugo/content/blog/hugo-and-jekyll-compared.md
  - hugo/content/blog/hugo-support-sorting-for-pages-and-more.md
  - hugo/content/blog/hugo-vs-jekyll-benchmark.md
  - hugo/content/blog/improved-collaboration-and-more.md
  - hugo/content/blog/instant-production-ready-scaffolding-with-create-static-site.md
  - hugo/content/blog/introducing-forestry-config-files.md
  - hugo/content/blog/introducing-media-management.md
  - hugo/content/blog/introducing-teams.md
  - hugo/content/blog/is-it-time-to-move-on-from-wordpress.md
  - hugo/content/blog/join-our-slack-community.md
  - hugo/content/blog/landing-page-create-static-site-copy.md
  - hugo/content/blog/layout-improvements.md
  - hugo/content/blog/march-27th-service-outage.md
  - hugo/content/blog/master-image-delivery-with-cloudinary.md
  - hugo/content/blog/migrating-to-key-based-authentication.md
  - hugo/content/blog/new-improve-media-gallery.md
  - hugo/content/blog/new-pricing-organization-accounts.md
  - hugo/content/blog/renaming-files-and-improving-team-editing.md
  - hugo/content/blog/sawmill-layout-composer-for-hugo-and-forestry.md
  - hugo/content/blog/search-with-algolia-in-hugo.md
  - hugo/content/blog/search-with-algolia-in-jekyll.md
  - hugo/content/blog/snippets-custom-content-sections-and-more.md
  - hugo/content/blog/spike-test-reset.md
  - hugo/content/blog/statyc-a-luxury-festival-for-hackers.md
  - hugo/content/blog/test.md
  - hugo/content/blog/the-new-forestry-io.md
  - hugo/content/blog/tina-cloud-the-next-forestry.md
  - hugo/content/blog/ubuild-a-new-theme-for-static-sites-using-blocks.md
  - hugo/content/blog/up-and-running-with-hugo-part-2.md
  - hugo/content/blog/up-and-running-with-hugo.md
  - hugo/content/blog/use-forestry-with-azure-devops-repos.md
  - hugo/content/blog/versioning-large-files-with-git-lfs.md
  - hugo/content/blog/vuepress-brings-your-documentation-to-life.md
  - hugo/content/blog/vuepress-support-beta.md
  - hugo/content/blog/what-are-instant-previews.md
  - hugo/content/blog/what-s-new-in-jekyll-3-4-0.md
  - hugo/content/blog/what-s-new-in-jekyll-3.8.md
  - hugo/content/blog/why-we-built-forestry.md
  - hugo/content/blog/why-we-created-a-git-backed-content-manager.md
  - hugo/content/blog/wysiwyg-formatting-in-front-matter.md
  - hugo/content/docs/_index.md
  - hugo/content/docs/faqs
  - hugo/content/docs/git-sync
  - hugo/content/docs/troubleshooting
  - hugo/content/terms.md
