query getPostsDocument($relativePath: String!) {
  getPostsDocument(relativePath: $relativePath) {
    data {
      ...PostsParts
    }
  }
}

query getPostsList {
  getPostsList {
    totalCount
    edges {
      node {
        id
        data {
          ...PostsParts
        }
      }
    }
  }
}

query getGlobalDocument($relativePath: String!) {
  getGlobalDocument(relativePath: $relativePath) {
    data {
      ...GlobalParts
    }
  }
}

query getGlobalList {
  getGlobalList {
    totalCount
    edges {
      node {
        id
        data {
          ...GlobalParts
        }
      }
    }
  }
}

query getAuthorsDocument($relativePath: String!) {
  getAuthorsDocument(relativePath: $relativePath) {
    data {
      ...AuthorsParts
    }
  }
}

query getAuthorsList {
  getAuthorsList {
    totalCount
    edges {
      node {
        id
        data {
          ...AuthorsParts
        }
      }
    }
  }
}

query getPagesDocument($relativePath: String!) {
  getPagesDocument(relativePath: $relativePath) {
    data {
      ...PagesParts
    }
  }
}

query getPagesList {
  getPagesList {
    totalCount
    edges {
      node {
        id
        data {
          ...PagesParts
        }
      }
    }
  }
}
