changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

initFields:
  version: 0.1.0
  dependencies:
    '@forestryio/build': 'workspace:packages/build'
  bin:
    'forestry:start': bin.js
  files: dist/*
  main: dist/index.js
  name: ''
  scripts:
    build: forestry-build
    graphiql: next dev -p 3001
    watch: forestry-watch
  typings: dist/types.d.ts

initScope: forestryio

npmAlwaysAuth: false

npmAuthIdent: '${FORESTRYIO_NPM_AUTH_IDENT:-must_supply_this_value_in_zshrc}'

npmAuthToken: '${FORESTRYIO_NPM_AUTH_TOKEN:-must_supply_this_value_in_zshrc}'

npmPublishRegistry: 'https://registry.npmjs.org'

npmRegistryServer: 'https://registry.npmjs.org'

npmScopes:
  forestryio:
    npmAlwaysAuth: false
    npmAuthIdent: '${FORESTRYIO_NPM_AUTH_IDENT:-must_supply_this_value_in_zshrc}'
    npmAuthToken: '${FORESTRYIO_NPM_AUTH_TOKEN:-must_supply_this_value_in_zshrc}'
    npmPublishRegistry: 'https://registry.npmjs.org'
    npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  '@fullhuman/postcss-purgecss@*':
    dependencies:
      postcss: ^8.2.10
  '@graphql-codegen/plugin-helpers@*':
    dependencies:
      graphql: ^14.6.0
  '@graphql-tools/links@6.2.1':
    dependencies:
      subscriptions-transport-ws: ^0.9.18
  '@octokit/rest@16.43.2':
    dependencies:
      '@octokit/core': ^3.3.0
      graphql: ^14.6.0
      subscriptions-transport-ws: ^0.9.18
  '@tinacms/fields@*':
    peerDependencies:
      '@tinacms/form-builder': latest
      '@tinacms/icons': latest
      '@tinacms/react-core': latest
      '@tinacms/react-forms': latest
      '@tinacms/styles': latest
      prop-types: '>=15'
      react-beautiful-dnd: ^11.0.5
      react-dismissible: ^1.3.0
  '@tinacms/form-builder@*':
    peerDependencies:
      final-form: ^4.18.2
      react-beautiful-dnd: ^11.0.5
      react-dom: ^16.13.0
      react-dismissible: ^1.3.0
  '@tinacms/icons@*':
    peerDependencies:
      react: ^16.13.0
  '@tinacms/react-forms@*':
    peerDependencies:
      final-form: ^4.18.2
      prop-types: '>=15'
  '@tinacms/react-toolbar@*':
    peerDependencies:
      react-beautiful-dnd: ^11.0.5
      react-dom: ^16.13.0
  '@tinacms/styles@*':
    peerDependencies:
      react: ^16.13.0
  codemirror-graphql@*:
    dependencies:
      graphql-language-service-utils: ^2.4.4
  express-graphql@*:
    dependencies:
      graphql: ^14.6.0
  graphiql@*:
    dependencies:
      prop-types: ^15.7.2
  next@9.4.2:
    dependencies:
      typescript: ^4.0.3
  react-beautiful-dnd@*:
    peerDependencies:
      react-dom: ^16.13.0
  react-dismissible@*:
    peerDependencies:
      react: ^16.13.0
  tinacms@*:
    dependencies:
      final-form: ^4.18.2
      prop-types: '>=15'
      react-beautiful-dnd: ^11.0.5
      react-dismissible: ^1.3.0
  tsup@*:
    dependencies:
      typescript: ^4.0.3
  create-react-class@*:
    dependencies:
      react: ^16.13.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-2.4.2.cjs
