import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-full bg-green-100 flex">
          <div className="h-screen w-16 bg-red-100 flex flex-col gap-2">
            <div>Logo</div>
            <div>Core</div>
            <div>Pix</div>
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
