fragment SidebarParts on Sidebar {
  title
  version
  locale
  type
  links {
    __typename
    ... on SidebarLinksLabel {
      title
    }
    ... on SidebarLinksPage {
      reference {
        ... on Page {
          title
          body
          slug
        }
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
      }
      children {
        __typename
        reference {
          ... on Page {
            title
            body
            slug
          }
          ... on Document {
            _sys {
              filename
              basename
              breadcrumbs
              path
              relativePath
              extension
            }
            id
          }
        }
      }
    }
  }
}

fragment PageParts on Page {
  title
  body
  slug
}
