fragment PageParts on Page {
  ... on PageToc {
    title
  }
  ... on PageLanding {
    title
  }
  ... on PageManual {
    title
  }
  ... on PageReference {
    title
  }
}

fragment ManualParts on Manual {
  ... on ManualToc {
    title
  }
  ... on ManualLanding {
    title
  }
  ... on ManualManual {
    title
  }
  ... on ManualReference {
    title
  }
}
