query documentation($relativePath: String!) {
  documentation(relativePath: $relativePath) {
    title
    tags {
      __typename
      reference {
        ... on Tag {
          title
          description
        }
        ... on Document {
          id
        }
        ... on Document {
          _internalSys: _sys {
            path
          }
        }
      }
    }
    body
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ... on Document {
      _internalSys: _sys {
        path
      }
    }
  }
}
